url: "https://ivankmk.tech" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Data Analytics" # the name of your site, e.g. ACME Corp.
description: "and market research"