menu:
- {name: 'research', url: '/research'}
- {name: 'projects', url: '/projects'}
- {name: 'courses', url: '/courses'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

research:
- {name: 'Real Estate in Luxembourg', url: 'luxembourg-real-estate'}


social:
- {icon: 'github', link: 'https://github.com/'}
- {icon: 'twitter', link: 'https://twitter.com/'}
