menu:
- {name: 'projects', url: '/projects'}
- {name: 'courses', url: '/courses'}
- {name: 'contact', url: 'mailto:rind.dungeon_0d@icloud.com'}

courses:
- {name: 'WIP', url: 'vector-calculus'}

projects:
- {name: 'Luxembourg Housing Market Analysis', subtitle: "Exploring the Dynamics of Luxembourg's Housing Market: A Comprehensive Monthly Analysis", url: 'project-luxembourg-housing-market', banner: '/assets/projects/luxembourg-housing-market/banner.png'}


social:
- {icon: 'envelope', link: "mailto:rind.dungeon_0d@icloud.com"}
